src/Entity/Test.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TestRepository")
 */
class Test
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string")
     */
    private $name;

    /**
     * @ORM\Column(type="string", unique=true)
     * @Gedmo\Slug(fields={"name"})
     *
     */
    private $slug;

    /**
     * @ORM\Column(type="integer")
     */
    private $failedAttempts = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $successAttempts = 0;

    /**
     * @ORM\Column(type="time")
     */
    private $timeLimit;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\OneToMany(
     *     targetEntity="Question",
     *     mappedBy="test",
     *     )
     */
    private $questions;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="createdTests")
     */
    private $author;

    /**
     * @ORM\ManyToMany(targetEntity="Tag", inversedBy="tests")
     */
    private $tags;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->questions = new ArrayCollection();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name)
    {
        $this->name = $name;
    }

    public function getFailedAttempts(): int
    {
        return $this->failedAttempts;
    }

    public function incFailedAttempts()
    {
        ++$this->failedAttempts;
    }

    public function getSuccessAttempts(): int
    {
        return $this->successAttempts;
    }

    public function incSuccessAttempts()
    {
        ++$this->successAttempts;
    }

    public function getAllAttempts(): int
    {
        return $this->failedAttempts + $this->successAttempts;
    }

    /**
     * Set number of failed attempts for instantly created item
     * Used only for fixtures, tests, e.g
     *
     * Use incFailedAttempts in production
     *
     * @param $failedAttempts
     */
    public function setFailedAttempts(int $failedAttempts)
    {
        if ($this->failedAttempts == 0) {
            $this->failedAttempts = $failedAttempts;
        }
    }

    /**
     * Set number of success attempts for instantly created item
     * Used only for fixtures, tests, e.g
     *
     * Use incSuccessAttempts in production
     *
     * @param $successAttempts
     */
    public function setSuccessAttempts(int $successAttempts)
    {
        if ($this->successAttempts == 0) {
            $this->successAttempts = $successAttempts;
        }
    }

    public function getSlug(): string
    {
        return $this->slug;
    }

    public function setSlug(string $slug)
    {
        $this->slug = $slug;
    }

    public function getTimeLimit(): \DateTime
    {
        return $this->timeLimit;
    }

    public function setTimeLimit(\DateTime $timeLimit)
    {
        $this->timeLimit = $timeLimit;

    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description)
    {
        $this->description = $description;
    }

    /**
     * @return ArrayCollection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag)
    {
        if ($this->tags->contains($tag)) {
            return;
        }

        $this->tags[] = $tag;
        // not needed for persistence, just keeping both sides in sync
        $tag->addTest($this);
    }

    public function removeTag(Tag $tag)
    {
        $this->tags->removeElement($tag);
        // not needed for persistence, just keeping both sides in sync
        if ($tag->getTests()->contains($this)) {
            $tag->removeTest($this);
        }
    }

    /**
     * @return ArrayCollection|Question[]
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question)
    {
        if ($this->questions->contains($question)) {
            return;
        }

        $this->questions[] = $question;

        $question->setTest($this);
    }

    public function removeQuestion(Question $question)
    {
        $this->questions->removeElement($question);

        $question->setTest(null);
    }

    public function getAuthor(): User
    {
        return $this->author;
    }

    public function setAuthor(User $author)
    {
        $this->author = $author;
    }
}

templates/_testlist.html.twig
{% block testlist %}
    {% for test in tests %}
        <div class="row">
            <div class="col">
                <a href="{{ path('test_preview', {
                    'slug': test.slug
                }) }}">
                    <h4>{{ test.name }}</h4>
                </a>
            </div>
            <div class="col">
                <span class="float-right">{{ test.successAttempts }} / {{ test.allAttempts }}</span>
            </div>
        </div>
        <div class="row">
            <div class="col">
                {% for tag in test.tags %}
                    <a href="{{ testByTagUrl(tag) }}"
                       class="badge badge-info">
                        {{ tag.name }}
                    </a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}
        {# todo use Encore#}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
              integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
              crossorigin="anonymous">
    {% endblock %}
</head>
<body>
<div class="container">
    {% block header %}
        <header class="row">
            <div class="col">
                {% set siteName %}
                    <h1>TestHub</h1>
                {% endset %}

                {% if isMainRoute is defined and isMainRoute == true %}
                    {{ siteName }}
                {% else %}
                    <a href="{{ path('main') }}">
                        {{ siteName }}
                    </a>
                {% endif %}
            </div>
            <div class="col">
                <div class="row float-right">
                    <div class="col ">
                        <a class="btn btn-info" href="">Sign In</a>
                        <a class="btn btn-info" href="">Sign Up</a>
                    </div>
                </div>
            </div>
        </header>
    {% endblock %}

    {% block body %}
        <div class="row">
            <div class="col-9">
                {% block main_column %}
                    <h2>
                        {{ block('title') }}
                    </h2>
                {% endblock %}
            </div>
            <div class="col">
                {% block right_column %}{% endblock %}
            </div>
        </div>
    {% endblock %}
</div>
{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
            integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
            integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
            crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>